version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20

  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - |
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
        if [ $? -eq 0 ]; then
          echo "Docker login succeeded."
        else
          echo "Docker login failed."
          exit 1
        fi
      - echo "Checking environment variables..."
      - |
        [ -z "$AWS_DEFAULT_REGION" ] && echo "AWS_DEFAULT_REGION is not set" && exit 1 || echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
        [ -z "$AWS_ACCOUNT_ID" ] && echo "AWS_ACCOUNT_ID is not set" && exit 1 || echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"
        [ -z "$IMAGE_REPO_NAME" ] && echo "IMAGE_REPO_NAME is not set" && exit 1 || echo "IMAGE_REPO_NAME: $IMAGE_REPO_NAME"
        [ -z "$CODEBUILD_BUILD_NUMBER" ] && echo "CODEBUILD_BUILD_NUMBER is not set" && exit 1 || echo "CODEBUILD_BUILD_NUMBER: $CODEBUILD_BUILD_NUMBER"

  build:
    commands:
      - echo "Starting build at `date`"
      - echo "Building the Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER .
      - echo "Tagging the Docker image..."
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER

  post_build:
    commands:
      - echo "Completed build at `date`"
      - echo "Pushing the Docker image to ECR..."
      - |
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER
        if [ $? -eq 0 ]; then
          echo "Docker push succeeded."
        else
          echo "Docker push failed."
          exit 1
        fi
      - echo "Cleaning up local Docker images..."
      - docker rmi $IMAGE_REPO_NAME:$CODEBUILD
